---
  - name: Re-create a redis container
    containers.podman.podman_container:
      name: sarthak
      image: httpd
      state: started
      detach: true
      exposed_ports:
        - 80
      ports:
        - 4444:80
      volumes: /home/:/usr/local/apache2/htdocs/