---
- name: Run container
  containers.podman.podman_container:
    name: hello-world-demo-container
    image: hello-world
    detach: no
    state: started
  register: podman_container_output 

- name: Show test output
  debug:
    var: podman_container_output